# Generated by Django 2.2.2 on 2019-09-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190626_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='bedrooms',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='peoples',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='toilets',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='begin_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
