# Generated by Django 2.2.2 on 2019-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190911_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='peoples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pet',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(null=True, upload_to='pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pet',
            name='toilets',
            field=models.IntegerField(default=0),
        ),
    ]
