# Generated by Django 2.2.2 on 2019-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190911_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='peoples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pet',
            name='toilets',
            field=models.IntegerField(default=0),
        ),
    ]
